### ISSUE TITLE
provide a keyword to get_specific_attribute_of_element

### ISSUE THREAD

**Issue by JimRevolutionist** [GDATASoftwareAG/robotframework-flaui#102]
@AndreGleichner

No matter what type of element, it owns attributes (like "Name", "IsOffscreen", "ClassName" and so on).

Now, in my case, I need to get the "SelectionItem.IsSelected" attribute of a RadioButton Element to know is it selecetd.

So, I think we can provide a keyword to realize this kind of function in our FlauiLibrary.

pseudocode like below:
def get_specific_attribute_of_element(self, attribute, xpath):
    """
        attribute (str) :  attribute name string
    """
    attribute_switcher = {
        "Name": lambda: self._get_element(xpath).Name,
        "ClassName": lambda: self._get_element(xpath).ClassName,
         "SelectionItem.IsSelected": lambda: self._get_element(xpath).SelectionItem.IsSelected,
        ......
    }
    return attribute_switcher .get(attribute)

**Comment by JimRevolutionist** [comment]
> @JimRevolutionist
> 
> Did you mean to check which item is selected?
> 
> By FlaUI you can currently do that with:
> 
> ```
> Select Radiobutton  ${XPATH_RADIO_BUTTON_TWO}
> ${STATE}   Get Radiobutton State  ${XPATH_RADIO_BUTTON_ONE}
> ${STATE_2}   Get Radiobutton State  ${XPATH_RADIO_BUTTON_TWO}
> ```
> 
> State is a Boolean which returns true if the xpath from element is enabled.
> 
> Is it what you mean? If not can you pls show it with an example from a wpf application.
> 
> The Selection.IsSelected property is in selection pattern which can be implemented as supported feature.

Yeah, keyword:"Get Radiobutton State" is available for my RadioButton case.

But in our FlaUILibrary libdoc document, I could not find such a keyword that: 
user input an attribute and an element xpath identifier(whatever element is a Window, a Button, a RadioButton, a CheckBox, a ), then keyword will return the inputted attribute of element.

I think such a keyword will be comprehensive and better for user to know any attribute of any element. 
What about your idea @Nepitwin

**Comment by Nepitwin** [comment]
@JimRevolutionist 

The possibility to reach all elements by selection item property from element if available is still a good idea and will be implemented to use them because you are right that all elements which implement such a property can be used afterwards.

This kewords will be implemented in near future as: 

- "Get Selected Property From Selection Item"  -> Returns True and False

- "Is Selected From Selection Item  <TRUE/FALSE>" <-- RAISE an FlauiException if item could not be found or property is not expected one

If any better ideas how to name it pls share it :).

**Comment by JimRevolutionist** [comment]
@Nepitwin 

I suggest: 

About "Get Selected Property From Selection Item" 
1. better to rename as "Get Property From Element";
2. Returns: the Property-Value of Element, its type maybe boolean,str,list,dict...

About "Is Selected From Selection Item <TRUE/FALSE>"
1. better to rename as "Is Property Supported" because old name is hard to straightforwardly read and understand.And "Is Property Supported" have 2 exception cases(see below).
2. will add a "ElementNotExists" into FlaUiError for case(element could not be found);
"PropertyNotSupported" already in FlaUiError for case(element does not have Selected-Property);

**Comment by Nepitwin** [comment]
@JimRevolutionist 

Ah okay i understand what the general idea is about Get Prorperty From Element. It should be a more generalized method which can be potential used to reflect all common properties from elements.

Then your first aproach from the initial idea was to support some actions which can be extended.

This idea is a good one because then afterwards it would be easier to maintain additional properties to support and return.

Sounds good for me.

**Comment by Nepitwin** [comment]
New upcoming Keyword implemented:

- Get Property From Element

Which includes supported operations:

        Supported operations:
        | "BACKGROUND_COLOR"            |
        | "FOREGROUND_COLOR"            |
        | "FONT_SIZE"                   |
        | "FONT_NAME"                   |
        | "FONT_WEIGHT"                 |
        | "CULTURE"                     |
        | "WINDOW_VISUAL_STATE"         |
        | "WINDOW_INTERACTION_STATE"    |
        | "TOGGLE_STATE"                |
        | "CAN_WINDOW_MINIMIZE"         |
        | "CAN_WINDOW_MAXIMIZE"         |
        | "IS_WINDOW_PATTERN_SUPPORTED" |
        | "IS_TEXT_PATTERN_SUPPORTED"   |
        | "IS_TOGGLE_PATTERN_SUPPORTED" |

An Is Property Supported is include into new keyword.
