### ISSUE TITLE
Possibility to use Relative path for element finding

### ISSUE THREAD

**Issue by savitakul** [GDATASoftwareAG/robotframework-flaui#109]
Hi,
We are checking if RobotFramework-Flaui is suitable for out test developement. Our team have around 1000+ tests in Coded UI and looking to shift to robotframework tests. We are considering the Flaui for test shift and new test development but during PoC we stuck on below issue -

Unable to locate element with Relative XPATH.
We have desktop application which has lot of pane and containers, the elements are located within these panes.
Example:
We are able to locate element with xpath:  /Window[@Name='XYZ']/Pane[2]/Pane[2]/ComboBox[2]

But this will be hard to maintain the XPATH, will it possible to access these elements with Relative XPATH, something like this -
//ComboBox[@name='abc'] ---> Search element anywhere on screen which is visible with given name ?

Appreciate the help!

**Comment by Nepitwin** [comment]
Hi,

Xpath can be used asweel by Tree Searching usage.

Here are some of Examples --> https://github.com/GDATASoftwareAG/robotframework-flaui/blob/documentation/examples/xpaths/xpaths.robot

https://github.com/GDATASoftwareAG/robotframework-flaui/blob/documentation/examples/xpaths/

https://gdatasoftwareag.github.io/robotframework-flaui/xpath.html

You are able to search on a Combobox pattern with your example.

Properties like @Name, @AutomationID or @Class can be used here. Automation ID should be used by general and can be set to most of all GUI Application to identify all gui elements directly or search for them if a pattern is generated.

Syntax with Array usage below is a way to go but for my opinion not recommended.

Hope that helps for you and you can adjust your PoC.

**Comment by savitakul** [comment]
Thanks @Nepitwin for direction to look into.
I have tried the provided simillar xpath to what provided in examples, but the outcome is failure to find xpath element.

We have application which responds well to UIA2, with UIA3 we get methodnotimplemented error.

Library           FlaUILibrary    UIA2

**Comment by noubar** [comment]
@savitakul Your problem is similar to the issue #82 
You are trying to access for example using a relative xpath like this : /Window[contains(@name,"Deposit/Loan")]//Edit[@name="Name:"]
What you should be aware of in this approach there is a linear search done by flaui to find a matching xpath and the first matching element will be taken.
This means under the window of /Window[contains(@name,"Deposit/Loan")] there is somewhere an edit element with the name = Name:
The flaui begins to search under the window"Deposit/Loan" in the list of first depth children of window if there is a matching element if not then the iterration will continue to first level children of the first child of window and so on. deeper and deeper until no element left.

The first matching element will be taken as the right element.
in your case if the test case is failing this means in the xpath tree of your app there is an edit element with name Name: ordered before your intended element. As @Nepitwin you should try to approach with automation ids or unique names which only and only the intended elment has it. Then there is no reason to the relative xpath to not to work.

**Comment by savitakul** [comment]
Thanks @noubar will try the approach with automation ids instead. I think that will be most reliable way to handle the xpath.
