### ISSUE TITLE
Getting Duplicate screen shots when ever script is getting failed

### ISSUE THREAD

**Issue by kasi861** [GDATASoftwareAG/robotframework-flaui#119]
Case1:
*** Settings ***
Library    FlaUILibrary      screenshot_on_failure=True
we are getting screen shots for every step as for passed steps also
case 2:
 Test Teardown  Take Screenshots On Failure   True
 we are getting  duplicate screen shots  for failed steps
case 3.
Teardown   Run Keyword If Test Failed    Capture Page Screenshot
we are getting  duplicate screen shots  for failed steps

**Comment by Nepitwin** [comment]
@kasi861 

Yes the current implementation from the screenshot library takes a lot of unecessary screenshots.

  * Current implementation handles to create screenshots and if testcase is successfully to delete all.

In general screenshots should only happen on keywords which are failing.
  * Keywords like Wait Until Keyword Succeeds create asweel screenshots because they got the failure state

Screenthost module has to be optimize to reduce amount of screenshots.

**Comment by JimRevolutionist** [comment]
I have repeated the problem about case 3 and found the bug code. But I could not repeat problem about case 2.

@kasi861  Would you provide all code in sample robot files to help us copy code and repeat all problems in your issue. 
or @Nepitwin  did you know how to repeat problem about case 2.

For example, below is my code to repeat problem about case 3.
![image](https://github.com/GDATASoftwareAG/robotframework-flaui/assets/126214844/435c30ca-db21-4871-b435-388b3ba9ab3e)

**Comment by Nepitwin** [comment]
In future screenshots can be minimized by blacklisting keywords to avoid multiple screenshots see more information in changelog or https://github.com/GDATASoftwareAG/robotframework-flaui/pull/123
