### ISSUE TITLE
[Enhancement] Get Current Window

### ISSUE THREAD

**Issue by JimRevolutionist** [GDATASoftwareAG/robotframework-flaui#129]
I want to talk with you about "Get Current Window", we can implement through python native libs in picture below, but not rf-flaui method. What about your idea @Nepitwin 
![image](https://github.com/GDATASoftwareAG/robotframework-flaui/assets/126214844/52d89a33-a797-46b2-b8f7-b62587e228b7)

**Comment by Nepitwin** [comment]
@JimRevolutionist 

That there may be an implementation in this regard is of course true. However, this is of course another way how you can integrate small own keywords for yourself in the robot framework.

That this functionality is offered via the Robotframework-FlaUI I do not see because it then implements different approaches for test automation.

The approach could be implemented on C# level of the FlaUI in the lib and then offer this.

This is a great strength of the Robotframework that you can quickly and flexibly integrate keywords on Python base. But mixing of many libraries leads in the end to long-term problems from my point of view even if the source code looks very small and simple.
