### ISSUE TITLE
Create screenshot as base64 encoded string instead of files

### ISSUE THREAD

**Issue by HackXIt** [GDATASoftwareAG/robotframework-flaui#192]
Storing screenshots as files is often not desired in the use-cases of the company I am working at.

We generally prefer having the screenshots embedded into the log files themselves as base64 encoded strings. This may enlarge the log files themselves, but it is much easier to exchange the log files, without consideration of file paths and similar.

In our Remote Library Interface, all screenshot functionalities use Base64 encoded images for logging instead of storing files.

----

I am already working on a PR to implement this functionality into this library in my fork:
https://github.com/HackXIt/robotframework-flaui

**Comment by chriskloe** [comment]
Sorry, no idea where I could get support thus I'm asking here directly:
Am I right that in case I'd prefer embedded screenshots in general I'd have to call Set Screenshot Log mode in every single Test Setup?
I'd prefer to set this during library initialization in a similar way like the screenshot_dir.

**Comment by Nepitwin** [comment]
Hi @chriskloe can you pls create a new issue ticket to extend this mode in Library usage so that you can on each Library import define this rule.

So i can adapt this implementation afterwards because this is not a big deal. Because you are actually right you have to use on each library import from flaui this keyword. would be an improement.
