### ISSUE TITLE
cannot handle pop up window

### ISSUE THREAD

**Issue by Bhavnasewani** [GDATASoftwareAG/robotframework-flaui#42]
Describe the bug
I have a desktop application screen that throws an error when you dont provide data as expected, unfortunately I dont see an automation id for this screen but I do see automation Id for a OK button on it.
I want to check in my script if this error pop up occured and I want to fail the test case in case of wrong data. If provided with correct data the pop up wont show and test cases should continue.

I tried 3 keywords:
Is Element Enabled //[@AutomationId='OkButton']
Element should not be Visible //[@AutomationId='OkButton']
Element should not Exist //*[@AutomationId='OkButton']

It does executes well is there is an error pop up coming up but when the data is clean the code fails throwing error Xpath not found or it would hang the project in pycharm and would work only when I restart everything

Code snippets
${ISErrPopupVisible} Is Element Enabled //*[@AutomationId='OkButton']

IF '${ISErrPopupVisible}'=='True'
Fail There is an issue with Input Data
ELSE
Log You have input correct data, please wait for the ouput to be generated
END

**Comment by Nepitwin** [comment]
Hi @Bhavnasewani

i see the issue for this checkup keywords.

All checkup keyword should return False if an Element does not Exists or the condition is false.
But in the current implementation all keywords throws an FlaUI Exception and breaks the tests for an element not found error message. It should be in this type of keywords of course FALSE return

This is only for the keyword handling by Is Keyword the case.

I will rework on this type of keywords and change the handling.

By the current status you can use a combination from core keywords by robotframework to get the correct status

https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Run Keyword And Return Status

Run Keyword And Return Status  <KEYWORD>

**Comment by Nepitwin** [comment]
@Bhavnasewani 

Sorry for the late request. I started to reevaluate your issue.

What you want to check is that an error popup is showing if input data is wrong.

Here we got now an issue on robotframework 4. The xpath does not exists and all keywords work like expected that they fail on your side because they can not verify your respose.

Your approaches are right. You have to combine them with Keyword And Return Status

${result}  Keyword And Return Status  Element Should Not Exist //*[@AutomationId='OkButton']
IF ${result}==${False}
    Log You have input correct data, please wait for the ouput to be generated
ELSE
    ${element_exists}  Element Should Not Exist //*[@AutomationId='OkButton']
    IF ${element_exists}==${True}
      Fail There is an issue with Input Data
    ELSE
      Log You have input correct data, please wait for the ouput to be generated
    END
END

By this combination you should checkup the input data and result. 
If the element will be found this keyword returns True because this does not fail. 
But you got know an issue, if this value will be return true you don't know if element does not exists or not? You only know that the operation was successfully. So you have to reevaluate that the element does not exists.

If it's failed because the xpath is not found because no error message popup it returns False so your input data is correct them.

The issue is here that the result is not a simple bool anymore because you have three states (Element does not exists (True) | Element exists (True) | Xpath not found (Error)

It's not a good design to combine error statements with return logic.
Robotframework 4 does not support like TRY EXCEPT usage but in Robotframework 5 it's a new feature.

What you want is similar code :

TRY
    ${element_exists}  Element Should Not Exist //*[@AutomationId='OkButton']
    IF ${element_exists}==${True}
      Fail There is an issue with Input Data
    ELSE
      Log You have input correct data, please wait for the ouput to be generated
    END
EXCEPT    Error XPath Not Found
        Log  You have input correct data, please wait for the ouput to be generated
END

This syntax will be available in robotframework 5 and i will extend the error handling by these exception blocks to create such a code on your test script for a better readablity.

https://github.com/GDATASoftwareAG/robotframework-flaui/issues/47

**Comment by Nepitwin** [comment]
Upcoming changes are:

All keywords currently throw an exception if xpath is not found for specific keyword it does not make sense
This keyword should return True if element exists otherwise False

- Element Should Exist
- Element Should Not Exist 

For this type of keywords the answer is always correct if xpath is not found. So this should always return true or false.

So your code will be simplified for robotframework 4 usage

${element_exists}  Element Should Not Exist //[@AutomationId='OkButton']
IF ${element_exists}==${True}
  Fail There is an issue with Input Data
ELSE
  Log You have input correct data, please wait for the ouput to be generated
END

**Comment by Nepitwin** [comment]
If you want to pre test these changes

- Checkout branch bugfix/popup#43
- Use keen.bat install cmd to build and locally install this version
- Additional use keen.bat build to build wheel file and install by pip seperatly
- Additional go to https://ci.appveyor.com/project/GDATACyberDefenseAG/robotframework-flaui/builds/42383383
  - Select an python build -> select artifacts -> download wheel file from build server
