### ISSUE TITLE
Click is not pressing on the correct tab

### ISSUE THREAD

**Issue by Mavnus04** [GDATASoftwareAG/robotframework-flaui#45]
At the top of my GUI is a series of tabs.
When using the `Select Tab Item By Name` keyword, I have no issue. 
However, if I use the `Click` keyword, it always clicks on the first tab in the row. 

    Test FlaUI tab presses
        [Tags]  Tab
        [Setup]  Attach application by name  ${WINDOW_NAME}
        Log to console  ...
        
        # Originally selects the correct tab, then mouse clicks on wrong tab
        Element Should Exist  xPath2
        Element Should Be Visible  xPath2
        Select Tab Item By Name  /Window[@Name='DevTool']/Tab  tab2Name
        Click  xPath2     # mouse clicks on wrong tab
        Sleep  3s

        # Selects the correct tab
        Element Should Exist  xPath1
        Element Should Be Visible  xPath1
        Select Tab Item By Name  /Window[@Name='DevTool']/Tab  tab1Name

Also, `Select Tab Item By Name` documentation state it returns the tabnames, similar to `Get Tab Items Names`

**Comment by Mavnus04** [comment]
I think I found part of the problem/solution?
When I set the xPath without the @Name= it still reports that the element exist, but is not pointing at the right element?
Here is an example with actual xPaths for my GUI

    Element Should Exist  /Window[@Name='DevTool']/Tab/TabItem[@Name='Bill Val Sim']
    Element Should Exist  /Window[@Name='DevTool']/Tab/TabItem['Bill Val Sim']
    Select Tab Item By Name  /Window[@Name='DevTool']/Tab  Bill Val Sim    # Selects the tab I am interested in
    Select Tab Item By Name  /Window[@Name='DevTool']/Tab  IOHub Sim    # Switch away from Bill Val tab to visually see switch back
    Click  /Window[@Name='DevTool']/Tab/TabItem[@Name='Bill Val Sim']    # Clicks the tab I am interested in
    Select Tab Item By Name  /Window[@Name='DevTool']/Tab  IOHub Sim    # Switch away from Bill Val tab to visually see switch back
    Click  /Window[@Name='DevTool']/Tab/TabItem['Bill Val Sim']  # Clicks    # Selects the first tab in the list of tabs

**Comment by Nepitwin** [comment]
Thanks for you response.

Ah i see what you try to do

/Window[@Name='DevTool']/Tab/TabItem['Bill Val Sim']

this xpath should not work by general because it should not know which search type should be used (Name, Id, HelpText).

In general you declare the full xpath by this click operation with a given name so

/Window[@Name='DevTool']/Tab/TabItem[@Name='Bill Val Sim'] is the correct syntax here.

Intresting to analyze why not an error for this case is dropped seems to me that if you don't use any property search modifier like id, name or helptext that a default property is used.

For this xpath i would general expect that an xpath could not be found for this case.

**Comment by Nepitwin** [comment]
I will analyze the code here from you example and update you what the default here will be used. Because i only transmit the xpath to the .net flaui core component :). So if i write the same example as .net i would see the same results here.

I will also make adjustments on this point.

**Comment by NoubarAkopian** [comment]
@Mavnus04 we cannot take the name as a default parameter for xpaths, because it could be needed to access an element without needing to assign the name or other attribute like classname or automationid of it because the xpath itself is unique. Furthermore it is even possible to assign them through there order number like. /window[10]/element[2] 
If you are in a static environment with minimal windows then it aslo could be handy. A general restriction in xpath syntax would only restrict the robot users reaching those items.

**Comment by Mavnus04** [comment]
The ordered number makes sense.  Could you check for a number [2] vs string['word']?  I am not seeing/understanding the use case for a string without the property.  Do you have an example of a non-number string within the final [''] without a property?

Yeah, it definitely was always clicking the first tab without the `@name`.

**Comment by noubar** [comment]
@Mavnus04
string['word'] there is no use case which is known to me.

**Comment by noubar** [comment]
I will suggest to close this issue.
