### ISSUE TITLE
Retrieve element attributes

### ISSUE THREAD

**Issue by andrejpu** [GDATASoftwareAG/robotframework-flaui#78]
Greetings,

Is it possible to gather any element attributes except 'Identification' attributes? 

Examples:
1. Excel: retrieve value from the cell: 
![image](https://user-images.githubusercontent.com/49622532/201060805-1539211b-1231-4169-ba6f-415234f12c87.png)

2. Excel: retrieve toggle state from TopAlign button:
![image](https://user-images.githubusercontent.com/49622532/201061256-d1135d73-ddb8-4490-958b-d42731d8c3b4.png)

3. Or any other attributes, like: Legacy|Accessible.State, SelectionItem
![image](https://user-images.githubusercontent.com/49622532/201062580-5817249b-8bd9-4993-a651-0f94a41eebf8.png)

**Comment by Nepitwin** [comment]
Currently selection by different properties is not supported. This issue is a duplicate by https://github.com/GDATASoftwareAG/robotframework-flaui/issues/72 which is the same request.

**Comment by andrejpu** [comment]
Closed as duplicate by #72.

**Comment by noubar** [comment]
@andrejpu You can get text of an excel cell by using the "Get Text From Textbox" keyword, because this keyword returns the value attribute. This means the following example works, which i have already tested:

${text}   Get Text From Textbox    /Window/Pane[5]/Pane[4]/Pane/DataGrid/DataItem[103]
Log To Console    ${text}
