### ISSUE TITLE
Set Window Visual State Request

### ISSUE THREAD

**Issue by Mavnus04** [GDATASoftwareAG/robotframework-flaui#92]
Excited to see some new development in this!  Thank you. :)

Was wondering if you plan on expanding on the "Window Visual State" keywords to include a Set Window Visual State, so that it can be changed to minimized, maximized, restore, etc.

Keep up the great work.

**Comment by Nepitwin** [comment]
Good Idea to make a Setter for Window Visual State Property.

I already inspect if this is possible and yes it can be done.

        var window = app.GetMainWindow(uia);

        if (!window.Patterns.Window.TryGetPattern(out var pattern))
        {
            return;
        }

        pattern.SetWindowVisualState(WindowVisualState.Maximized);
        pattern.SetWindowVisualState(WindowVisualState.Minimized);
        pattern.SetWindowVisualState(WindowVisualState.Normal);

For an easier handling i would suggest to implement three keywords.

MaximizeWindow - It will asweel checked if window could be maximized if not an error will be called
MinimizeWindow - It will be asweel checked if window could be minimized if not an error will be called
NormalizeWindow  - Window should be always normalized

Asweel checker keywords would be implenmented

CanWindowMinimize - Returns True If Window Can Be Minimized Otherwise False
CanWindowMaxmimize - Returns True If Window Can Be Maximized Otherwise False

**Comment by Mavnus04** [comment]
Sorry if this is a different issue, but seems related...

Just wrote this bit of Robot code to try setting the window visual state myself.

```
Change GUI window visual state
    [Documentation]
    ...     Keyword
    [Arguments]  ${windowName}  ${state}
    Log  windowName=${windowName}
    ${xPathToFormat} =  Convert To String  /Window[@Name='{}']
    ${xPath} =  Format String  ${xPathToFormat}  ${windowName}
    FlaUILibrary.Focus  ${xPath}
    ${newXPath} =  Catenate  ${xPath}  /TitleBar/Button[@Name='${state}']
    ${newElement} =  Create Dictionary  xPath=${newXPath}
    Click on GUI element  ${newElement}

Click on GUI element
    [Arguments]  ${element}
    Log Many  ${element}
    GUI Element Should Exist And Be Visible  ${element}
    FlaUILibrary.Click  ${element}[xPath]

GUI Element Should Exist And Be Visible 
    [Arguments]     ${element}
    Log Many  ${element}
    FlaUILibrary.Element Should Exist  ${element}[xPath]
    FlaUILibrary.Element Should Be Visible  ${element}[xPath]
```

When I try to run `Restore` after `Minimize`, it will give me `FlaUiError: Element position could not be found because it is hidden.`  Even though `FlaUILibrary.Element Should Be Visible` returns True/Pass

**Comment by Mavnus04** [comment]
@Nepitwin  That is great to hear!  Hopefully I won't need my additional robot code that I just posted.   Sorry, must have been writing it while you posting too.
